
SELECT
    CUSTOMER_ID,
    NUMBER_OF_ORDERS,
    TOTAL_AMOUNT_SPENT_USD,
    {{ get_discount_eligibility('NUMBER_OF_ORDERS', 'TOTAL_AMOUNT_SPENT_USD') }} AS IS_ELIGIBLE_FOR_DISCOUNT,
    {{ calculate_discount('IS_ELIGIBLE_FOR_DISCOUNT', 'NUMBER_OF_ORDERS', 'TOTAL_AMOUNT_SPENT_USD') }} AS DISCOUNT_USD
FROM  {{ ref('int_customers_orders_joined') }}