version: 2

models:
  - name: stg_order_items
    columns:
      - name: order_id
        description: "Order ID reference"
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: product_id
        description: "Product ID reference"
        tests:
          - relationships:
              to: ref('stg_products')
              field: product_id